### ISSUE TITLE
Check plugin breaks when controller restarts

### ISSUE THREAD

**Issue by hardoverflow** [hardoverflow/check-unifi#4]
If the UniFi Network Application restarts, there is a time period where the plugin breaks.

```bash
./check_unifi.py -H 'controller.fqdn.com' --mode 'stats' --ssl --user 'monitoring' --pass 'securepassword' --site-id 'default' --port 443 --perfdata
```

```bash
Traceback (most recent call last):
  File "/Users/hardoverflow/Library/Caches/pypoetry/virtualenvs/check-unifi-OAJjHLue-py3.11/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hardoverflow/.pyenv/versions/3.11.0/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hardoverflow/.pyenv/versions/3.11.0/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hardoverflow/.pyenv/versions/3.11.0/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hardoverflow/development/gitlab.com/hardoverflow/infrastructure/check-unifi/./check_unifi.py", line 292, in <module>
    main()
  File "/Users/hardoverflow/development/gitlab.com/hardoverflow/infrastructure/check-unifi/./check_unifi.py", line 288, in main
    fmt_output(check_site_stats(args))
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hardoverflow/development/gitlab.com/hardoverflow/infrastructure/check-unifi/./check_unifi.py", line 220, in check_site_stats
    blob.append(resp.json())
                ^^^^^^^^^^^
  File "/Users/hardoverflow/Library/Caches/pypoetry/virtualenvs/check-unifi-OAJjHLue-py3.11/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by hardoverflow** [comment]
What should the expected output for this check during this time frame?
